Readme

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,27 +1,38 @@
-#!/usr/bin/env ruby
-require "pathname"
-require "fileutils"
-include FileUtils
+#!/usr/bin/env sh
 
-# path to your application root.
-APP_ROOT = Pathname.new File.expand_path("../../", __FILE__)
+set -e
 
-def system!(*args)
-  system(*args) || abort("\n== Command #{args} failed ==")
-end
+echo "[setup]: Installing required languages"
+if [ -x "$(command -v asdf)" ]; then
+  set +e
+  asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git 2>/dev/null
+  asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git 2>/dev/null
+  set -e
 
-chdir APP_ROOT do
-  puts "== Installing dependencies =="
-  system! "gem install bundler --conservative"
-  system("bundle check") || system!("bundle install")
-  system!("yarn install")
+  asdf install
 
-  puts "\n== Preparing database =="
-  system! "bin/rails db:setup"
+  echo "[setup]: Installing bundler"
 
-  puts "\n== Removing old logs and tempfiles =="
-  system! "bin/rails log:clear tmp:clear"
+  gem install bundler
+else
+  echo "
+    We are using asdf (https://github.com/asdf-vm/asdf) to manage tool
+    dependencies, since it was not found on your system we cannot ensure that you
+    are using the correct versions of all the tools. Please install it and run
+    this script again, or proceed at your own peril.
+  "
+fi
 
-puts "\n== Restarting application server =="
-  system! "bin/rails restart"
-end
+echo "[setup] Setting up .env file"
+cp .env.sample .env
+
+echo "[setup]: Installing dependencies with bundler and yarn"
+bundle check || bundle install
+yarn
+
+echo "[setup]: Preparing database"
+bundle exec rake db:create || true
+bundle exec rake db:migrate
+bundle exec rake db:test:prepare
+
+echo "You're good to go. Run bin/server to get the app running."
